services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - appnet

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    expose:
      - "5173"
    depends_on:
      - backend
    networks:
      - appnet

  backend:
    build: ./backend
    expose:
      - "4000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/practice
    depends_on:
      - mongodb
    networks:
      - appnet

  mongodb:
    image: mongo:8.0
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - appnet

networks:
  appnet:

volumes:
  mongo_data: