server { # server 설정 시작
  listen 80; # 80 port로 들어오는 요청을 받겠다.

  # location 뒤의 경로: browser가 보낸 요청의 경로를 보고 분기
  location /graphql { 
    proxy_pass http://backend:4000;
    proxy_set_header Host $host; # backend에 broswer 요청 정보를 넘길 때 사라지지 않게 보존
    proxy_set_header X-Real-IP $remote_addr; # backend에 broswer 요청 정보를 넘길 때 사라지지 않게 보존
  }

  location / { # // "/" 경로로 들어오면 frontend라는 service의 5173 port로 넘겨
    proxy_pass http://frontend:5173;
    proxy_http_version 1.1; # HMR용
    proxy_set_header Upgrade $http_upgrade; # HMR용
    proxy_set_header Connection "upgrade"; # HMR용
    proxy_set_header Host $host; # vite server에 broswer 요청 정보를 넘길 때 사라지지 않게 보존
  }
}